################################################################################
# Site settings
################################################################################
title: "Jason's Basecamp"
tagline: "" # a short description used when page.title is not defined
description: >- # this means to ignore newlines until "baseurl:"
  I am a person who is passionate about education. I enjoy inspiring people
  around me and taking in the knowledge that they have to share. Life isn’t
  always easy and we all have struggles, some more than others, but with a
  little understanding we can help each other overcome situations in order to
  succeed. This perhaps is why I enjoy being an educator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://basecamp.jasonsclassroom.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Jason K
logo: ""
publications:
  - title: CAEPA
    img: "/publication-caepa.png"
    url: https://www.caepa.org
  - title: Jasons' Classroom
    img: "/publication-jasonsclassroom.png"
    url: https://www.jasonsclassroom.com
  - title: Standards
    img: "/publication-standards.png"
    url: https://standards.jasonsclassroom.com
social:
  name: Jason K
  links:
    - https://www.codepen.io/champa720
    - https://www.github.com/champa720
    - https://www.linkedin.com/in/jason-k-17111717
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   yandex: 1234
#   baidu: 1234
# google_analytics: UA-XXXXXXXX-X

################################################################################
# Build settings
# https://material.io/resources/color
################################################################################
theme: null
future: false
date_format: "%Y %B %d" # http://shopify.github.io/liquid/filters/date/
collections_dir: archive
collections:
  - ideas
  # - learnings
  # - media
  # - readings
  # - reflections
  # - resouces
  # - thoughts
defaults:
  -
    scope:
      type: posts
    values:
      layout: markdown
  -
    scope:
      type: pages
    values:
      layout: markdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

################################################################################
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _sass
  - .jekyll-cache/     # default
  - .sass-cache/       # default
  - Gemfile            # default
  - Gemfile.lock       # default
  - gemfiles/          # default
  - node_modules/      # default
  - package-lock.json
  - package.json
  - README.md
  - vendor/bundle/     # default
  - vendor/cache/      # default
  - vendor/gems/       # default
  - vendor/ruby/       # default
  - webpack.config.js
  - webpack.style-bundle.js
