INHERIT: ../mkdocs.yml
edit_uri: edit/main/mkdocs/basecamp/docs/
site_description: >
    I am a person who is passionate about education. I enjoy inspiring people around me and taking in the knowledge that they have to share. Life isn’t always easy and we all have struggles, some more than others, but with a little understanding we can help each other overcome and succeed.

    This perhaps is why I enjoy working in education.
site_dir: ../../_site/basecamp
site_url: https://j.sohvi.design/basecamp
extra:
  homepage: https://j.sohvi.design
theme:
  palette:
    # primary: white
    # accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: pink
      toggle:
       icon: material/weather-night
       name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
       icon: material/weather-sunny
       name: Switch to dark mode
