INHERIT: ../mkdocs.yml
edit_uri: edit/main/mkdocs/basecamp/docs/
site_description: >
    I am a person who is passionate about education.
    I enjoy inspiring people around me and taking in the knowledge that they have to share.
    Life isn’t always easy and we all have struggles, some more than others,
    but with a little understanding we can help each other overcome situations in order to succeed.
    This perhaps is why I enjoy being an educator.
site_dir: ../../_site/basecamp
site_url: https://j.sohvi.design/basecamp
extra:
  homepage: https://j.sohvi.design
theme:
  palette:
    primary: white
    accent: pink
