source 'https://rubygems.org'

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

################################################################################
# GitHub pages
# https://github.com/github/pages-gem
################################################################################
#
# require 'json'
# require 'open-uri'
# versions = JSON.parse(open('https://pages.github.com/versions.json').read)
#
# gem 'github-pages', versions['github-pages'], group: :jekyll_plugins
