repo_name: champa720/basecamp
repo_url: https://github.com/champa720/basecamp
site_name: Jason Sohvi Noska
site_url: https://j.sohvi.design

################################################################################
theme:
  custom_dir: overrides
  favicon: assets/images/logo--light.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.expand
    # - navigation.sections
    # - navigation.tracking
  icon:
    logo: material/heart
    repo: fontawesome/brands/github
  name: material
  palette:
    scheme: slate
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode

################################################################################
extra:
  homepage: https://j.sohvi.design
  blog:
    words_read_per_minute: 120 # efficient words per minute
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jason-n-17111717
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/playlist?list=PLqpuloa9jUuJMllESrcOHaUlZWxMzReXa
    - icon: fontawesome/brands/soundcloud
      link: http://soundcloud.com/champa720
    - icon: fontawesome/brands/github
      link: http://github.com/champa720

################################################################################
extra_css:
  - assets/stylesheets/extend.css

################################################################################
markdown_extensions:

  # Python Markdown
  - admonition          # Admonition
  - meta
  - toc:
      permalink: true   # Header links
      toc_depth: 2      # Default 6
  - attr_list           # Images
  - md_in_html          # Images
  - tables              # Data tables

  # Python Markdown Extensions
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
